name = "学歴"
key = "education"
order = 30

[[items]]
date = "2021-3"
title = "秋田県立秋田高等学校理数科 卒業"

[[items]]
date = "2021-04"
title = "名古屋大学情報学部 自然情報学科 入学"

[[items]]
date = "2025-03"
title = "名古屋大学情報学部 自然情報学科 卒業"

[[items]]
date = "2025-04"
title = "名古屋大学大学院情報学研究科 数理情報学専攻 修士課程 入学"
