name = "その他"
key = "others"
order = 80

[[items]]
title = "GitHub: [kentakom1213](https://github.com/kentakom1213)"

[[items]]
title = "AtCoder: [powell](https://atcoder.jp/users/powell)"

[[items]]
title = "グラフ可視化アプリ: [Graph Editor](https://kentakom1213.github.io/graph-editor/)"
