title = "甲本健太 | KOMOTO Kenta"
default_language = "ja"
google_site_verification = "7Pja-gmgJ-5jKr55Kqomfcqz0kXFHnoUAHNyGARYCDo"

[build]
output_dir = "docs"
output_file = "index.html"

[assets]
dir = "assets"
mount_path = "/assets"
