[name]
ja = "甲本 健太"
en = "KOMOTO Kenta"

[affiliation]
affiliation = "名古屋大学大学院 情報学研究科 数理情報学専攻"

[contact]
email = "komoto.kenta.v1(at)s.mail.nagoya-u.ac.jp"

lead = """
グラフアルゴリズム，列挙アルゴリズムを研究しています．
"""
